general:
  testnet: true
parameters:
  pinata_api: ""
  pinata_secret_api: ""
  to_who: ''
  minter: ''
  minter_seed: ''
  provider_testnet: ""
  contract_address_testnet: ''
  provider: ""
  contract_address: ''
  contract_filename: ''
filepaths:
  video: ''
  picture: ''
  rosbag: ''
